<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="DompetKu — aplikasi pencatatan keuangan pribadi yang sederhana, aman, dan cerdas.">
    <meta name="theme-color" content="#0A1128"><link rel="canonical" href="{{ url('/') }}">
    <link rel="icon" href="{{ asset('favicon.ico') }}" sizes="48x48"><link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}"><link rel="manifest" href="{{ asset('site.webmanifest') }}">
    <meta property="og:type" content="website"><meta property="og:site_name" content="DompetKu"><meta property="og:title" content="DompetKu — Aplikasi Keuangan Pribadi"><meta property="og:description" content="Kelola pemasukan, pengeluaran, dan anggaran bulanan dengan mudah.">
    <title>DompetKu — Kelola Keuangan Pribadi</title>
    <script>(function(){try{if(localStorage.getItem('theme')!=='light')document.documentElement.classList.add('dark')}catch(e){}})()</script>
    <link rel="preconnect" href="https://fonts.bunny.net" crossorigin><link href="https://fonts.bunny.net/css?family=figtree:400,500,600,700,800&display=swap" rel="stylesheet" />
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="font-sans text-slate-900 dark:text-white antialiased">
<div class="min-h-screen relative isolate overflow-hidden bg-slate-50 dark:bg-navy-950">
    <div class="page-grid absolute inset-0 -z-20 opacity-70"></div><div class="absolute -top-48 left-1/2 -z-10 h-[36rem] w-[36rem] -translate-x-1/2 rounded-full bg-blue-400/20 blur-3xl dark:bg-navy-400/20"></div>
    <header class="mx-auto flex w-full max-w-6xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10">
        <a href="{{ url('/') }}" class="flex items-center gap-2.5 rounded-xl"><x-application-logo class="h-10 w-10 drop-shadow-md" /><span class="text-lg font-extrabold tracking-tight">DompetKu</span></a>
        <div class="flex items-center gap-2 sm:gap-3"><a href="{{ route('login') }}" class="rounded-xl px-3 py-2 text-sm font-semibold text-slate-700 transition hover:bg-white/80 hover:text-blue-700 dark:text-white/85 dark:hover:bg-navy-800 sm:px-4">Masuk</a><a href="{{ route('register') }}" class="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white shadow-brand transition hover:-translate-y-0.5 hover:bg-blue-700 sm:px-5">Mulai gratis</a></div>
    </header>
    <main class="mx-auto grid w-full max-w-6xl items-center gap-12 px-5 pb-16 pt-10 sm:px-8 sm:pb-24 sm:pt-16 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:pt-20">
        <section class="max-w-2xl">
            <div class="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-200/80 bg-white/70 px-3 py-1.5 text-xs font-bold text-blue-700 shadow-sm backdrop-blur dark:border-navy-500/40 dark:bg-navy-900/70 dark:text-navy-200"><span class="h-2 w-2 rounded-full bg-emerald-500"></span>Catat. Pahami. Kendalikan.</div>
            <h1 class="text-4xl font-extrabold leading-[1.08] tracking-tight text-slate-950 dark:text-white sm:text-5xl lg:text-6xl">Keuangan lebih tenang, <span class="text-blue-600 dark:text-navy-300">setiap hari.</span></h1>
            <p class="mt-6 max-w-xl text-base leading-7 text-slate-600 dark:text-white/70 sm:text-lg">DompetKu membantu kamu mencatat transaksi, memantau anggaran, dan memahami arah keuangan tanpa spreadsheet yang rumit.</p>
            <div class="mt-8 flex flex-col gap-3 sm:flex-row"><a href="{{ route('register') }}" class="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-bold text-white shadow-brand transition hover:-translate-y-0.5 hover:bg-blue-700">Buat akun gratis <span aria-hidden="true">→</span></a><a href="{{ route('login') }}" class="inline-flex items-center justify-center rounded-xl border border-slate-200 bg-white/80 px-6 py-3.5 text-sm font-bold text-slate-700 transition hover:border-blue-200 hover:bg-white dark:border-navy-700 dark:bg-navy-900/70 dark:text-white">Saya sudah punya akun</a></div>
            <div class="mt-8 flex flex-wrap gap-x-5 gap-y-3 text-xs font-semibold text-slate-500 dark:text-white/60"><span>✓ Tanpa biaya pendaftaran</span><span>✓ Privasi saldo di tanganmu</span></div>
        </section>
        <section aria-label="Contoh ringkasan keuangan" class="relative mx-auto w-full max-w-md lg:max-w-none"><div class="absolute -inset-5 -z-10 rounded-[2rem] bg-blue-500/10 blur-2xl dark:bg-navy-400/15"></div><div class="overflow-hidden rounded-3xl border border-slate-200/90 bg-white/95 p-5 shadow-2xl shadow-blue-950/10 backdrop-blur dark:border-navy-700 dark:bg-navy-900/95 sm:p-6"><div class="flex items-center justify-between"><div><p class="text-xs font-semibold text-slate-500 dark:text-white/60">Ringkasan bulan ini</p><p class="mt-1 text-sm font-bold">Bulan berjalan</p></div><span class="rounded-lg bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300">Terkendali</span></div><div class="mt-5 rounded-2xl bg-gradient-to-br from-blue-700 to-blue-500 p-5 text-white shadow-lg shadow-blue-600/20 dark:from-navy-600 dark:to-navy-500"><p class="text-xs font-medium text-white/75">Saldo tersedia</p><p class="mt-1 text-3xl font-extrabold tracking-tight">Rp 4.850.000</p><div class="mt-5 grid grid-cols-2 gap-3 border-t border-white/20 pt-4 text-xs"><div><p class="text-white/65">Pemasukan</p><p class="mt-1 font-bold">Rp 7.500.000</p></div><div><p class="text-white/65">Pengeluaran</p><p class="mt-1 font-bold">Rp 2.650.000</p></div></div></div><div class="mt-5 space-y-3"><div class="flex items-center justify-between"><div><p class="text-sm font-bold">Makan & minum</p><p class="text-[11px] text-slate-500 dark:text-white/55">Hari ini</p></div><span class="text-sm font-bold text-rose-500">− Rp 68.000</span></div><div class="flex items-center justify-between"><div><p class="text-sm font-bold">Pendapatan proyek</p><p class="text-[11px] text-slate-500 dark:text-white/55">Kemarin</p></div><span class="text-sm font-bold text-emerald-600 dark:text-emerald-400">+ Rp 1.250.000</span></div></div></div></section>
    </main>
    <section class="mx-auto grid w-full max-w-6xl gap-4 px-5 pb-16 sm:grid-cols-3 sm:px-8 lg:px-10">@foreach ([['Catat cepat', 'Tambah pemasukan atau pengeluaran dalam beberapa langkah sederhana.'], ['Lihat pola', 'Grafik ringkas membantu kamu memahami kebiasaan belanja.'], ['Tetap terkendali', 'Atur anggaran dan cek progresnya kapan saja.']] as [$title, $description])<div class="rounded-2xl border border-slate-200/80 bg-white/65 p-5 backdrop-blur dark:border-navy-800 dark:bg-navy-900/60"><h2 class="text-sm font-bold">{{ $title }}</h2><p class="mt-1.5 text-xs leading-5 text-slate-500 dark:text-white/60">{{ $description }}</p></div>@endforeach</section>
    <footer class="pb-8 text-center text-xs text-slate-400 dark:text-white/40">© {{ date('Y') }} DompetKu · Kelola keuanganmu dengan mudah dan aman.</footer>
</div>
</body></html>
